#pragma once
enum SHDELETEFLAG {
	SHDELETE_DEFAULT			= 1<<0,
	SHDELETE_NOUI				= 1<<1,
	SHDELETE_COMPLETEDELETE		= 1<<2,
};
BOOL SHDeleteFile(LPCTSTR lpFile, SHDELETEFLAG shf=SHDELETE_DEFAULT);
